namespace MyJetWallet.Unlimint.Models;

public enum PaymentAlternativeType
{
    Boleto,
    Baloto,
    Davivienda,
    Loterica,
    Spei,
    Oxxo,
    Efecty,
    DepositExpressBrasil,
    PagoEfectivo,
    Pix,
    QqCodePicPay,
    Codi,
    Pse,
    Soriana,
    ComercialMexicana,
    Bancomer,
    Walmart,
    BodegaAurrera,
    SamsClub,
    Superama,
    Calimax,
    TiendasExtra,
    CirculoK,
    SevenEleven,
    Telecomm,
    Banorte,
    FarmaciasBenavides,
    FarmaciasdelAhorro,
    ElAsturiano,
    Waldos,
    Alsuper,
    Kiosko,
    FarmaciasSantaMaria,
    FarmaciasLaMasBarata,
    FarmaciasRoma,
    Farmacias911,
    FarmaciasEconomicas,
    FarmaciasMedicity,
    Rianxeira,
    WesternUnion,
    ZonaPago,

    
    

}